# Generated by Django 5.1.3 on 2024-11-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furnituredetection',
            old_name='image',
            new_name='image_data',
        ),
        migrations.RemoveField(
            model_name='furnituredetection',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='furnituredetection',
            name='position',
        ),
        migrations.RemoveField(
            model_name='room',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='furnituredetection',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furnituredetection',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furnituredetection',
            name='width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='furnituredetection',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='furnituredetection',
            name='furniture_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='furnituredetection',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
