# Generated by Django 5.1.3 on 2024-11-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_room_height_room_length_room_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituredetection',
            name='frame_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='furnituredetection',
            name='video_data',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
