# Generated by Django 5.1.3 on 2024-11-17 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_room_last_scan_room_volume_alter_room_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scan_duration', models.IntegerField()),
                ('detection_count', models.IntegerField()),
                ('average_confidence', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.room')),
            ],
        ),
    ]
